### ISSUE TITLE
the math symbol doesn't show up properly in anki

### ISSUE THREAD

**Issue by chs33** [debanjandhar12/logseq-anki-sync#14]
the math symbol doesn't show up properly in Anki.

in logseq 
![image](https://user-images.githubusercontent.com/16418270/147903892-b1d5b9f7-7da1-4e6b-aab2-1afdf692388e.png)

when show up in anki
![image](https://user-images.githubusercontent.com/16418270/147903854-398ffd28-0ca0-42d9-94b2-08d73d25c06a.png)

**Comment by debanjandhar12** [comment]
Thanks. This seems to a bug in the current parser (markdownit). 
The bug however doesn't happen in the new parser (mldocs) which is under development. An release version with new parser will be made within next 2 weeks so it will get fixed automatically once that happens.

**Comment by debanjandhar12** [comment]
This has been tested and fixed in v1.0.0.

**Comment by chs33** [comment]
Thanks for the new fix. Looks like it works for a lot of my math expression but have still have issue displaying when deal with \text command

For example in logseq:
![image](https://user-images.githubusercontent.com/16418270/150698590-f8099594-eb51-451a-b112-791e724ca1b8.png)
which will showed up as:
![image](https://user-images.githubusercontent.com/16418270/150698600-4ff5577a-c498-491f-8600-9a1b68408239.png)

in anki it is not showed properly:
![image](https://user-images.githubusercontent.com/16418270/150698639-6b84eafe-f8aa-4ed7-a89f-0c69866e1720.png)
