### ISSUE TITLE
Setup fails - Error: [deferred timeout] async call #1022

### ISSUE THREAD

**Issue by yingzhu146** [debanjandhar12/logseq-anki-sync#23]
**Describe the bug**

<img width="500" alt="image" src="https://user-images.githubusercontent.com/59233975/150711388-80df72f7-9fa5-4ca6-bc8d-3a0eceb93bb1.png">

This persists over restarts of both Anki and Logseq

**Steps to Reproduce:**

1. install anki sync from marketplace
2. download anki
3. install ankiconnector plugin for anki
4. Click "Sync button"
6. Give AnkiConnect addon permissions in anki app
7. Pop-up error message is shown
8. Open DevTools, shows error message above (same as popup)

**Expected behavior**

**Developer console screenshot:**
<img width="535" alt="image" src="https://user-images.githubusercontent.com/59233975/150711267-8d97bbf2-2d23-4107-9877-064765b2f494.png">

**Device Information (please complete the following information):**

 - OS with version:v1.0.0 on Macbook Air, Monterey
 - Logseq Anki Sync Plugin Version: 1.0.0
 - Anki Version:  Version ⁨2.1.49 (dc80804a)⁩
 - AnkiConnect Addon  Version: not sure where to get, but I just installed today with 2055492159
 - Logseq Version:0.5.9

**Comment by debanjandhar12** [comment]
I believe this has been fixed and will be included with v2.0.0 next week.

**Comment by yingzhu146** [comment]
just tested again - still not working 
<img width="534" alt="image" src="https://user-images.githubusercontent.com/59233975/162575109-9809c6a7-188c-4dd3-8921-fc6d517fe737.png">
