### ISSUE TITLE
There are problems with syncing mp4 files to Anki

### ISSUE THREAD

**Issue by imxw** [debanjandhar12/logseq-anki-sync#249]
**Describe the bug**
The mp4 file wasn't successfully imported into Anki; instead, it just showed where the file is located in Logseq.
![image](https://github.com/debanjandhar12/logseq-anki-sync/assets/16207029/d53c2cbe-2916-41d9-928b-784a224f6b03)

**Expected behavior**
![image](https://github.com/debanjandhar12/logseq-anki-sync/assets/16207029/8f25d74e-60d6-4230-ab42-df0ef0c7990c)

**Device Information (please complete the following information):**

-   OS with version: MacOS
-   Logseq Anki Sync Plugin Version: v6.0.0
-   Anki Version: ⁨23.12.1 (1a1d4d54)⁩
-   AnkiConnect Addon Version: 2.1.x "min_point_version": 45, "max_point_version": 45, "branch_index": 1 Updated 2024-01-02.
-   Logseq Version: 0.10.3

**Comment by imxw** [comment]
<img width="891" alt="image" src="https://github.com/debanjandhar12/logseq-anki-sync/assets/16207029/cf6fd11c-4717-4c4e-9ec5-ce9b2468d9ab">
Add an image, it seems there is a problem with storing assets in LazyAnkiNoteManager.ts.

**Comment by debanjandhar12** [comment]
Is this fixed now?

**Comment by imxw** [comment]
still can't play
<img width="463" alt="image" src="https://github.com/debanjandhar12/logseq-anki-sync/assets/16207029/7fa6d71c-142a-4696-9ebf-8542a19943c1">
