### ISSUE TITLE
Rendering issue with double }} in multiline cards

### ISSUE THREAD

**Issue by debanjandhar12** [debanjandhar12/logseq-anki-sync#25]
Rendering issue with double `}}` in multiline cards math.

For example in logseq:
![image](https://user-images.githubusercontent.com/16418270/150698590-f8099594-eb51-451a-b112-791e724ca1b8.png)
which will showed up as:
![image](https://user-images.githubusercontent.com/16418270/150698600-4ff5577a-c498-491f-8600-9a1b68408239.png)

in anki it is not showed properly:
![image](https://user-images.githubusercontent.com/16418270/150698639-6b84eafe-f8aa-4ed7-a89f-0c69866e1720.png)

_Originally posted by @chs33 in https://github.com/debanjandhar12/logseq-anki-sync/issues/14#issuecomment-1019570944_

**Comment by debanjandhar12** [comment]
This is now fixed in v1.0.1.

**Comment by chs33** [comment]
I updated to v1.0.1. using the same my example above, the problem still exist.

**Comment by chs33** [comment]
> This is now fixed in v1.0.1.

I updated to v1.0.1. using the same my example above, the problem still exists.

**Comment by debanjandhar12** [comment]
> > This is now fixed in v1.0.1.
> 
> I updated to v1.0.1. using the same my example above, the problem still exists.

Thanks for the report. This has been fixed and will be included in the next version next week.
