### ISSUE TITLE
Error: [deferred timeout] async call #4364

### ISSUE THREAD

**Issue by IsaiahSimon** [debanjandhar12/logseq-anki-sync#58]
**Describe the bug**
Error: [deferred timeout] async call #4364

-This error persists over restarts of both Anki and Logseq
-This error persists over refreshes and reindexes of the Logseq graph.
-This error was intermittent prior to logseq-anki-sync v2.0.0, 
(re-indexing Logseq graph used to help after multiple tries, but now this error is constant and the plugin has become unuseable.)

**Steps to Reproduce:**

1. install logseq-anki-sync from marketplace
2. open Anki
3. install AnkiConnect plugin for anki using (2055492159)
4. Verify AnkiConnect is running by accessing localhost:8765 in browser
5. Open DevTools
6. Click "Sync button" in Loqseq
7. Click "Yes" on Logseq wants to access Anki message (only first time)
8. DevTools shows error message above  
9. Pop-up error message is shown in Loqseq

**Expected behavior**

-Normally the sync plugin would run, create cards using cloze syntax in Logseq, then present the summary prompt to click "Yes" to proceed with card creation/updates/deletions in Anki. 
-The process would take a few minutes while Anki flashes, then present a "success" popup in Logseq, with updated cards made in Anki. 
-I've created about 1200 automatic cards across multiple "per-page" decks this way prior to this bug.

**Developer console screenshot:**
![Screen Shot 2022-03-22 at 9 17 35 AM](https://user-images.githubusercontent.com/60068759/159490764-431c22a8-8b21-4ac3-b0cf-b7cbe050b73c.png)

**Device Information (please complete the following information):**
 - OS with version: MacBook Pro, Monterey, Version: 12.2.1
 - Logseq Anki Sync Plugin Version: v2.0.0
 - Anki Version: 2.1.49 (dc80804a)
 - AnkiConnect Addon Version: v.6 (obtained by accessing localhost:8765 in browser)
 - Logseq Version: 0.6.0, 0.6.3 and 0.6.4 (same outcome)

**Comment by debanjandhar12** [comment]
Thanks for the bug report, I will look into this by the end of the week.

**Comment by IsaiahSimon** [comment]
Thank you for your hard work on this! Let me know if you need any additional info need on my end to help resolve this bug.

**Comment by debanjandhar12** [comment]
Yes, can you update to v2.1.2 and see if the error persist? If it does, can you make a screenshot of the Developer console screenshot like above? It would help me identify what part of the code is causing the error.

**Comment by IsaiahSimon** [comment]
Ok, updated to v2.1.2, cleared the Dev console, restarted Logseq, and launched updated plugin. I got the following 3 errors:

First two errors (expanded for more detail):
![Screen Shot 2022-03-28 at 11 47 19 AM](https://user-images.githubusercontent.com/60068759/160437200-86c6d187-7198-445f-b7b4-507d05ab38ed.png)

3rd error (expanded for more detail):
![Screen Shot 2022-03-28 at 11 47 40 AM](https://user-images.githubusercontent.com/60068759/160437436-e30b0cb2-8f98-48b7-be06-7da620c8c494.png)

**Comment by YangWaldon** [comment]
![image](https://user-images.githubusercontent.com/49675185/166168405-bc416fa8-ca8c-4428-b0ed-46db03357fc0.png)
I also encountered this problem on the latest version 2.5.0

**Comment by YangWaldon** [comment]
I do not know why this issue was closed,because it have not been solved in the latest logseq plugin and anki.exe
![image](https://user-images.githubusercontent.com/49675185/166727369-6f00c439-3ee2-4158-b244-42232469e690.png)

**Comment by debanjandhar12** [comment]
- > I do not know why this issue was closed,because it have not been solved in the latest logseq plugin and anki.exe ![image](https://user-images.githubusercontent.com/49675185/166727369-6f00c439-3ee2-4158-b244-42232469e690.png)

   I might have probably closed it by mistake when trying to close a duplicate (to centralize information regarding the issue). Opps.
- It took some time to investigate the problem as this seems mac specific and I didnt have one so in the end I had to deploy one in cloud. Apologies.
- Now, for the main topic:
- - The error is caused from logseq api probably due to repeated calls to `logseq.Editor.getBlock`. 
- - Some of the unneeded calls to the above function in cloze notes is already removed in the plugin's latest version. However, this is definitely not a fix.
- - It might be possible that user iteration with UI causes repeated calls to `logseq.Editor.getBlock` to be allowed?
- - If the above is true then shifting some code from multiline cards should solve the problem.
- In order to actually solve the problem I plan to talk to Charlie (or look at the logseq's plugin api code myself if I get some free time) for confirming my assumptions. I will try to push a complete fix by next two weeks if possible.
- Lastly, I added some debugging statements related to this bug in the latest release. It would be of great help if some of you can run the latest version of the plugin and make some screenshot of the dev console similar to the screenshots of [IsaiahSimon](https://github.com/IsaiahSimon) above. Thanks!

**Comment by debanjandhar12** [comment]
Any updates on this? Is the issue still occuring in v2.6.3?

**Comment by WaytrueDeng** [comment]
> Any updates on this? Is the issue still occuring in v2.6.3?

yes still exist 
![image](https://user-images.githubusercontent.com/61548208/168200614-4ae3e42b-2658-4911-963a-5d64d796d3b5.png)

**Comment by WaytrueDeng** [comment]
> Any updates on this? Is the issue still occuring in v2.6.3?

this could be fixed if I delete all before cards to reduce the amout of cards

**Comment by debanjandhar12** [comment]
> > Any updates on this? Is the issue still occuring in v2.6.3?
> 
> yes still exist ![image](https://user-images.githubusercontent.com/61548208/168200614-4ae3e42b-2658-4911-963a-5d64d796d3b5.png)

Thanks for the help @WaytrueDeng. Can you update to the new v2.6.4 and check again? Also, if possible please include the Developer Console logs.

**Comment by debanjandhar12** [comment]
Closing this as I believe this has been solved? Please reopen in-case it occurs again.
